version: '3'
services:
  jekyll:
    ports:
      - "4000:4000"
    image: jekyll/jekyll
    volumes:
      - .:/jekyll
    environment:
      - JEKYLL_ENV=development
    entrypoint: ["jekyll", "serve", "--drafts"]
    working_dir: /jekyll